#!/bin/bash

# CIE CI/CD Setup Script
# This script helps set up the CI/CD environment for the CIE project

set -e

echo "🚀 CIE CI/CD Setup Script"
echo "========================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Python version
    if command_exists python3; then
        PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
        if [[ "$PYTHON_VERSION" == 3.13* ]]; then
            log_success "Python 3.13+ found: $PYTHON_VERSION"
        else
            log_error "Python 3.13+ required, found: $PYTHON_VERSION"
            exit 1
        fi
    else
        log_error "Python 3 not found. Please install Python 3.13+"
        exit 1
    fi
    
    # Check Docker
    if command_exists docker; then
        log_success "Docker found"
    else
        log_warning "Docker not found. Container-based CI will not work."
    fi
    
    # Check Dagger
    if command_exists dagger; then
        DAGGER_VERSION=$(dagger version 2>/dev/null | head -1 || echo "unknown")
        log_success "Dagger found: $DAGGER_VERSION"
    else
        log_warning "Dagger not found. Dagger-based CI will not work."
    fi
    
    # Check Git
    if command_exists git; then
        log_success "Git found"
    else
        log_error "Git not found. Please install Git"
        exit 1
    fi
}

# Install Dagger
install_dagger() {
    log_info "Installing Dagger..."
    
    if command_exists dagger; then
        log_info "Dagger already installed"
        return 0
    fi
    
    log_info "Downloading and installing Dagger..."
    curl -L https://dl.dagger.io/dagger/install.sh | sh
    
    # Move to /usr/local/bin if possible
    if [ -w /usr/local/bin ]; then
        sudo mv bin/dagger /usr/local/bin/
        log_success "Dagger installed to /usr/local/bin"
    else
        log_warning "Dagger installed to ./bin/dagger. Add to PATH manually."
        echo "export PATH=\$PATH:$(pwd)/bin" >> ~/.bashrc
    fi
}

# Set up environment variables
setup_env_vars() {
    log_info "Setting up environment variables..."
    
    ENV_FILE=".env"
    if [ -f "$ENV_FILE" ]; then
        log_warning ".env file already exists. Backing up..."
        cp "$ENV_FILE" "$ENV_FILE.backup"
    fi
    
    cat > "$ENV_FILE" << EOF
# CIE Environment Configuration
# Generated by setup-ci.sh

# AI Model API Keys (required for real model usage)
# KIMI_API_KEY=your-kimi-api-key-here
# OPENAI_API_KEY=your-openai-api-key-here

# Database Configuration (optional)
# POSTGRES_PASSWORD=secure-password-here

# Monitoring Configuration (optional)
# GRAFANA_PASSWORD=admin-password-here

# Container Registry (optional)
# REGISTRY=ghcr.io
# IMAGE_TAG=latest

# CI/CD Configuration
PYTHON_VERSION=3.13
DAGGER_VERSION=0.9.3

# Development Settings
CIE_CONFIG_DIR=~/.cie
CIE_EXPERIMENTS_DIR=~/.cie/experiments
EOF
    
    log_success "Environment file created: $ENV_FILE"
    log_info "Please edit $ENV_FILE and add your API keys"
}

# Install development dependencies
install_dev_deps() {
    log_info "Installing development dependencies..."
    
    if [ -f "pyproject.toml" ]; then
        log_info "Installing from pyproject.toml..."
        pip install -e ".[dev]"
        log_success "Development dependencies installed"
    else
        log_error "pyproject.toml not found. Are you in the right directory?"
        exit 1
    fi
}

# Set up Git hooks
setup_git_hooks() {
    log_info "Setting up Git hooks..."
    
    HOOKS_DIR=".git/hooks"
    if [ ! -d ".git" ]; then
        log_warning "Not a Git repository. Skipping Git hooks setup."
        return 0
    fi
    
    # Pre-commit hook
    cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# CIE pre-commit hook

echo "🔍 Running pre-commit checks..."

# Run linting
echo "Running ruff check..."
ruff check cie/ || exit 1

# Check formatting
echo "Checking black formatting..."
black --check cie/ || exit 1

# Run type checking
echo "Running mypy type checking..."
mypy cie/ --ignore-missing-imports || exit 1

# Run tests
echo "Running quick tests..."
pytest tests/ -x --tb=short || exit 1

echo "✅ Pre-commit checks passed"
EOF
    
    chmod +x "$HOOKS_DIR/pre-commit"
    log_success "Pre-commit hook installed"
    
    # Pre-push hook
    cat > "$HOOKS_DIR/pre-push" << 'EOF'
#!/bin/bash
# CIE pre-push hook

echo "🚀 Running pre-push checks..."

# Run full test suite
echo "Running full test suite..."
pytest tests/ -v --cov=cie || exit 1

echo "✅ Pre-push checks passed"
EOF
    
    chmod +x "$HOOKS_DIR/pre-push"
    log_success "Pre-push hook installed"
}

# Create CI configuration
create_ci_config() {
    log_info "Creating CI configuration..."
    
    # Create GitHub Actions workflows directory
    mkdir -p .github/workflows
    
    # Create Dagger configuration
    mkdir -p ci
    
    log_success "CI configuration directories created"
}

# Set up Docker environment
setup_docker() {
    log_info "Setting up Docker environment..."
    
    if ! command_exists docker; then
        log_warning "Docker not found. Skipping Docker setup."
        return 0
    fi
    
    # Test Docker
    if docker info >/dev/null 2>&1; then
        log_success "Docker is running"
        
        # Build development image
        log_info "Building development Docker image..."
        docker build --target development -t cie:dev .
        log_success "Development Docker image built"
        
        # Test the image
        log_info "Testing Docker image..."
        docker run --rm cie:dev python -c "import cie; print('✅ Docker image works')"
        log_success "Docker image test passed"
        
    else
        log_error "Docker is not running. Please start Docker daemon."
        return 1
    fi
}

# Test the setup
test_setup() {
    log_info "Testing the setup..."
    
    # Test Python import
    log_info "Testing Python import..."
    python -c "import cie; print('✅ CIE import successful')"
    
    # Test CLI
    log_info "Testing CLI..."
    cie --help > /dev/null
    log_success "CLI test passed"
    
    # Test basic functionality
    log_info "Testing basic functionality..."
    python -c "
from cie.core.backend import CIEBackend
from cie.config.settings import CIEConfig
config = CIEConfig()
config.model.provider = 'mock'
backend = CIEBackend(config)
print('✅ Backend initialization successful')
backend.close()
"
    log_success "Basic functionality test passed"
}

# Main setup function
main() {
    log_info "Starting CIE CI/CD setup..."
    
    check_prerequisites
    
    # Interactive setup
    echo
    echo "What would you like to set up?"
    echo "1) Complete setup (recommended)"
    echo "2) Minimal setup (basic tools only)"
    echo "3) Custom setup"
    echo -n "Choose option (1-3): "
    read -r choice
    
    case $choice in
        1)
            log_info "Running complete setup..."
            install_dagger
            setup_env_vars
            install_dev_deps
            setup_git_hooks
            create_ci_config
            setup_docker
            test_setup
            ;;
        2)
            log_info "Running minimal setup..."
            setup_env_vars
            install_dev_deps
            test_setup
            ;;
        3)
            log_info "Running custom setup..."
            echo -n "Install Dagger? (y/n): "
            read -r install_dagger_choice
            if [[ "$install_dagger_choice" == "y" ]]; then
                install_dagger
            fi
            
            echo -n "Set up environment variables? (y/n): "
            read -r setup_env_choice
            if [[ "$setup_env_choice" == "y" ]]; then
                setup_env_vars
            fi
            
            echo -n "Install development dependencies? (y/n): "
            read -r install_deps_choice
            if [[ "$install_deps_choice" == "y" ]]; then
                install_dev_deps
            fi
            
            echo -n "Set up Git hooks? (y/n): "
            read -r setup_hooks_choice
            if [[ "$setup_hooks_choice" == "y" ]]; then
                setup_git_hooks
            fi
            
            echo -n "Set up Docker? (y/n): "
            read -r setup_docker_choice
            if [[ "$setup_docker_choice" == "y" ]]; then
                setup_docker
            fi
            
            test_setup
            ;;
        *)
            log_error "Invalid choice. Please run the script again."
            exit 1
            ;;
    esac
    
    # Final summary
    echo
    log_success "CI/CD setup completed successfully!"
    echo
    echo "📋 Next steps:"
    echo "1. Edit .env file and add your API keys"
    echo "2. Run tests: pytest"
    echo "3. Try the CLI: cie --help"
    echo "4. Start TUI: cie tui"
    echo "5. Run CI locally: dagger call ci --source=."
    echo
    echo "📖 Documentation:"
    echo "- CI/CD Guide: CI_CD.md"
    echo "- Project Guide: AGENTS.md"
    echo "- README: README.md"
    echo
    log_info "Happy optimizing! 🚀"
}

# Make script executable
chmod +x "$0"

# Run main function
main "$@"